tasks:
  - name: opentofu
    env: 
      TF_LOG: DEBUG
    before: |
      cd $THEIA_WORKSPACE_ROOT
      source ./bin/install_tofu
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $THEIA_WORKSPACE_ROOT
      source ./bin/install_awscli